# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

state_dens_rcpp <- function(linear_pred, stratum, n_states, sampling_densities, n_obs) {
    .Call('_hmmSSF_state_dens_rcpp', PACKAGE = 'hmmSSF', linear_pred, stratum, n_states, sampling_densities, n_obs)
}

